version: '3'
services:
    redis:
        ports:
            - 6379:6379
        image: redis:4.0.5-alpine
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        networks:
          - redis-net
        volumes:
          - redis-data:/data
networks:
    redis-net:
volumes:
    redis-data: