http:
  port: 8449
admin:
  port: 8490
  host: localhost
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  adminBackend:
    url: https://localhost:8490
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - rewrite
pipelines:
  adminAPI:
    apiEndpoints:
      - admin
    policies:
      - rewrite:
          - condition:
              name: pathmatch
              match: /adminapi/:route*
            action:
              rewrite: /:route
      - proxy:
          - action:
              serviceEndpoint: adminBackend
  httpbin:
    apiEndpoints:
      - general
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
apiEndpoints:
  general:
    host: localhost
    paths: '/ip'
  admin:
    host: localhost
    paths: "/adminapi/*"