http:
  port: 8449
admin:
  port: 8490
  host: localhost
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  dropship:
    url: 'http://localhost:4999'
  adminBackend:
    url: 'http://localhost:8490'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - rewrite
pipelines:
  adminAPI:
    apiEndpoints:
      - admin
    policies:
      - key-auth:
      - rewrite:
          - condition:
              name: pathmatch
              match: /ctrlpoint/:route*
            action:
              rewrite: /:route
      - proxy:
          - action:
              serviceEndpoint: adminBackend
  httpbin:
    apiEndpoints:
      - general
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  dropship:
    apiEndpoints:
      - dropship
    policies:
      - key-auth:
      - rewrite:
        - condition:
            name: pathmatch
            match: /dropship/:route*
          action:
            rewrite: /api/:route
      - proxy:
        - action:
            serviceEndpoint: dropship
            changeOrigin: true
apiEndpoints:
  general:
    host: localhost
    paths: '/ip'
  admin:
    host: localhost
    paths: "/ctrlpoint/*"
    scopes:
      - "admin"
  dropship:
    - host: localhost
      methods: ["GET"]
      paths: 
        - '/dropship/orders/'
        - '/dropship/orders/:id/status'
        - '/dropship/orders/:id/tracking'

    - host: localhost
      methods: ["POST"]
      paths:
        - '/dropship/orders'