http:
  port: 8449
admin:
  port: 8490
  host: localhost
serviceEndpoints:
  dropship:
    url: 'http://dsgql:4000'
  adminBackend:
    url: 'http://localhost:8490'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - rewrite
pipelines:
  adminAPI:
    apiEndpoints:
      - admin
    policies:
      - key-auth:
      - rewrite:
          - condition:
              name: pathmatch
              match: /ctrlpoint/:route*
            action:
              rewrite: /:route
      - log:
        - action:
            message: ${req.method} ${req.originalUrl} -> ${req.url}              
      - proxy:
          - action:
              serviceEndpoint: adminBackend
  dropship:
    apiEndpoints:
      - dropship
    policies:
      - key-auth:
      - rewrite:
          - condition:
              name: pathmatch
              match: /dropship/:route*
            action:
              rewrite: /
      - log:
          - action:
              message: ${req.method} ${req.originalUrl} -> ${req.url}
      - proxy:
          - action:
              serviceEndpoint: dropship
apiEndpoints:
  admin:
    host: "*"
    paths: "/ctrlpoint/*"
    scopes:
      - "admin"
  dropship:
    host: "*"
    path: "/dropship/"
    scopes:
      - "dropship"