# Core
db:
  redis:
    host: redis
    port: 6379
    namespace: EG
    password: ${REDIS_PW}

#plugins:
  # express-gateway-plugin-example:
  #   param1: 'param from system.config' 

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: insomniacVidyaG8mr
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000

plugins:
  rewrite:
    package: express-gateway-plugin-rewrite